SCREEN_SIZE=(25,50)
SCREEN_COLOR=(0,153,0)
EXPLOSION='explotion.png'
FLAG_IMG='flag.png'
GRASS_IMG='grass.png'
INJURY_IMG='injury.png'
MINE_IMG='mine.png'
SNAKE_IMG='snake.png'
SOLDIER_IMG='soldier.png'
SOLDIER2_IMG='soldier (2).png'
SOLDIER_NIGHT_IMG='soldier_nigth.png'
FLAG="flag"
SOLDIER="soldier"
EMPTY="empty"